### ISSUE TITLE
Tracking issue for PR "Add support for Github sources"

### ISSUE THREAD

**Issue by jaimergp** [ForgottenProgramme/grayskull#7]
The gist of that feature request is to provide `grayskull` with the ability of accepting a GitHub repo (and potentially other `git` providers like GitLab) as the `sdist` (source distribution) origin.

The way Grayskull works now with `PyPI` packages is roughly:

1. The user specifies a package name
2. Grayskull looks for that package name in PyPI
3. Tries to fetch the PyPI metadata
4. Downloads the `setup.py` sdist tarball and runs it to obtain more metadata
5. Merges both metadata sources in a single dictionary
6. Uses the final metadata to write the recipe

For a GitHub source, we can only obtain the metadata from the `setup.py`, so the process would be:

1. The user specifies a GitHub repository URL. We detect this by checking for `http[s]://` in the specified package "name".
2. We build the `archive` URL to download the code corresponding to the last commit in the default branch.
3. Pass this URL to the `sdist` download mechanism, which auto-extracts and runs the `setup.py` for us.
4. Once we have obtained the metadata, we can delegate to the recipe-writing functions used above like normal.

That looks simple, but there are some gotchas we need to worry about:

* Obtaining the metadata from the repository only might mean that some required keys in the metadata are missing. We might need to secure these through other means. If not possible, we might need to change some of the code that `grayskull` already has to make it more resilient to missing keys; e.g. instead of assuming a given key will be always present, check first and handle the missing value with a sensible default.
* GitHub's default branch used to be `master`, but the platform is moving towards `main` to use a more inclusive language. Individual repos can also change it to something else through their settings. Essentially, we cannot assume `master` _is_ the default branch; we need to query GitHub for that. There's an [API for that](https://stackoverflow.com/a/16501903).
  * At some point, we might not even want the last commit in the default branch, but the last _release_ instead. We will need to check wether the repository has releases (or tags) and get the corresponding git reference.
 

So, the work plan for this:

1. [x] Make sure we have a good example repository URL. The repository should have `master` as default for now. We will change this as we go, but for the beginning this assumption is good enough for testing.
2. [x] Detect whether the user passed a package name or a GitHub URL.
3. [x] Build the URL for the archive tarball for `master`.
4. [x] Make sure this can be ingested directly by the `sdist` download and extract machinery. If not, adjust accordingly.
5. [x] Make sure the extracted tarball can be taken by the "run `setup.py` and obtain metadata" machinery. If not, adjust accordingly.
6. [x] If the changes to the existing codepaths are too intricate, consider adding a subclass for `PyPi` where we override as needed. Choosing between one class or the other can be done during the CLI parsing.

All these tasks can have their own issues opened if needed. PRs should target one task at a time, and reference the corresponding issue.
